-- MySQL Script generated by MySQL Workbench
-- seg 18 nov 2019 10:44:18 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todo-expotec2019
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todo-expotec2019
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todo-expotec2019` DEFAULT CHARACTER SET utf8 ;
USE `todo-expotec2019` ;

-- -----------------------------------------------------
-- Table `todo-expotec2019`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo-expotec2019`.`user` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(150) NOT NULL,
  `login` VARCHAR(60) NOT NULL,
  `password` VARCHAR(300) NOT NULL,
  `accessToken` VARCHAR(100) NOT NULL,
  `authKey` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo-expotec2019`.`columns`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo-expotec2019`.`columns` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `archived` TINYINT(1) NOT NULL DEFAULT 0,
  `user_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_list_user1_idx` (`user_id` ASC),
  CONSTRAINT `fk_list_user1`
    FOREIGN KEY (`user_id`)
    REFERENCES `todo-expotec2019`.`user` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todo-expotec2019`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todo-expotec2019`.`card` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `todo` VARCHAR(100) NOT NULL,
  `order` INT NOT NULL,
  `archived` TINYINT(1) NOT NULL DEFAULT 0,
  `column_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_card_list_idx` (`column_id` ASC),
  CONSTRAINT `fk_card_list`
    FOREIGN KEY (`column_id`)
    REFERENCES `todo-expotec2019`.`columns` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
